---

- name: "transmission-daemon | Ensure transmission-daemon installed"
  package:
    name: transmission-daemon
    state: present

- name: "transmission-daemon | Create required directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ transmission_user[ansible_distribution] }}"
    group: "{{ transmission_group[ansible_distribution] }}"
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"
    - "{{ transmission_config_dir[ansible_distribution] }}"

- name: "transmission-daemon | Create settings file"
  template:
    src: settings.json.j2
    dest: "{{ transmission_config_dir[ansible_distribution] }}/settings.json"
    owner: "{{ transmission_user[ansible_distribution] }}"
    group: "{{ transmission_group[ansible_distribution] }}"
    mode: 0600
  notify: "transmission-daemon | reload settings"

- name: "transmission-daemon | Ensure transmission-daemon running"
  service:
    name: transmission-daemon
    state: started
